# Generated by Django 4.2.5 on 2023-09-18 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satuan',
            fields=[
                ('id_satuan', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_satuan', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('nama_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_product', models.CharField(max_length=255)),
                ('harga', models.CharField()),
                ('id_kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.satuan')),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.status')),
            ],
        ),
    ]
