# Generated by Django 4.2.5 on 2023-09-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nomor',
            field=models.IntegerField(null=True),
        ),
    ]
