# Generated by Django 4.2.5 on 2023-09-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_nomor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satuan', to='product.satuan'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.status'),
        ),
    ]
