# Generated by Django 4.2.5 on 2023-09-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_id_kategori_alter_product_id_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id_kategori',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id_status',
        ),
    ]
