# Generated by Django 4.2.5 on 2023-09-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_id_kategori_remove_product_id_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_kategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='satuan', to='product.satuan'),
        ),
        migrations.AddField(
            model_name='product',
            name='id_status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='product.status'),
        ),
    ]
