# Generated by Django 4.2.5 on 2023-09-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_id_kategori_product_id_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='id_kategori',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_status',
            new_name='status',
        ),
    ]
