# Generated by Django 4.2.5 on 2023-09-21 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_id_kategori_product_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='product.satuan'),
        ),
    ]
